// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr_VHRN_A1L68JjTKTaqp58BPgYvw3hC8',
    appId: '1:1074953507434:web:fcd51d31f71e497afcb013',
    messagingSenderId: '1074953507434',
    projectId: 'aspire-gm',
    authDomain: 'aspire-gm.firebaseapp.com',
    storageBucket: 'aspire-gm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX8dcsK_QvsyUwhQmro7du9vHOrti88FA',
    appId: '1:1074953507434:android:f4f6fc75ccde59ccfcb013',
    messagingSenderId: '1074953507434',
    projectId: 'aspire-gm',
    storageBucket: 'aspire-gm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkG0ecRnwYPnv6GvTz-0aHF7jaZke0A1Q',
    appId: '1:1074953507434:ios:a350ad25f3f60d98fcb013',
    messagingSenderId: '1074953507434',
    projectId: 'aspire-gm',
    storageBucket: 'aspire-gm.firebasestorage.app',
    iosBundleId: 'com.example.aspire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkG0ecRnwYPnv6GvTz-0aHF7jaZke0A1Q',
    appId: '1:1074953507434:ios:a350ad25f3f60d98fcb013',
    messagingSenderId: '1074953507434',
    projectId: 'aspire-gm',
    storageBucket: 'aspire-gm.firebasestorage.app',
    iosBundleId: 'com.example.aspire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr_VHRN_A1L68JjTKTaqp58BPgYvw3hC8',
    appId: '1:1074953507434:web:e31ca47764375775fcb013',
    messagingSenderId: '1074953507434',
    projectId: 'aspire-gm',
    authDomain: 'aspire-gm.firebaseapp.com',
    storageBucket: 'aspire-gm.firebasestorage.app',
  );
}
